
document.addEventListener("DOMContentLoaded", function() {
    const textElement = document.getElementById("text");
    const infoBox = document.getElementById("info-box");

    let openCount = 0; // Contatore delle aperture del box informativo
    const alertMessages = [
        "Sei il mio tutto.",
        "Il tuo sorriso illumina la mia giornata.",
        "Non vedo l’ora di abbracciarti.",
        "Sei la mia felicità.",
        "Ogni momento con te è speciale.",
        "Ti amo più di quanto le parole possano dire.",
		"Sei il mio sogno diventato realtà.",
		"Con te, ogni giorno è un’avventura.",
		"Sei il mio rifugio sicuro.",
		"Il mio cuore batte solo per te.",
		"Sei la mia ragione di vita.",
		"Ogni tuo bacio è un dono prezioso.",
		"Sei la parte migliore di me.",
		"Ti amo oggi, domani e per sempre.",
		"Con te, mi sento a casa.",
    ];

    // Funzione per mostrare informazioni quando una parola è cliccata
    function showInfoBox(word) {
        const info = getWordInfo(word);
        if (info) {
            infoBox.textContent = info;
            infoBox.classList.remove('hidden');

            openCount++;
            if (openCount % 10 === 0) {
                const randomAlert = alertMessages[Math.floor(Math.random() * alertMessages.length)];
                alert(randomAlert);
            }
        } else {
            infoBox.classList.add('hidden');
        }
    }

    // Funzione per ottenere informazioni su una parola
    function getWordInfo(word) {
        const info = {
            "Ik":"nominativo del pronome personale di prima persona 'io' (antico sassone, nel caso di aat. sarebbe stato 'ih', non ha mutazione consonantica)",
            "gihorta":"preterito indicativo di prima persona singolare di gihoren, verbo debole di 1 classe",
            "đat":"accusativo singolare del dimostrativo, usato anche come articolo (forma sassone per la d col taglio e la t)",
            "seggen":"dal verbo sagjian, verbo debole di 3 classe (forma anglosassone per la geminazione)",
            "dat":"accusativo singolare del dimostrativo, usato anche come articolo (forma sassone per la d col taglio e la t)",
            "sih":"accusativo plurale del pronome riflessivo",
            "urhettun":"3 persona plurale del preterito del verbo urhetan, verbo forte 7 classe (forma sassone, per la e lunga originata da ai, in aat avremmo heirzan)",
            "ænon":"dativo singolare femminile del numerale 'en' (1)",
            "moutin":"dativo singolare di muodim",
            "Hiltibrant":"Hildebrando",
            "enti":"congiunzione aat ('and' con la II MUT)",
            "Hađubrant":"Adubrando",
            "untar":"preposizione (forma tedesca, richiama 'under')",
            "herium":"dativo plurale retto da 'undar' (la preposizione regge il dativo) di heri (= esercito)",
            "tuem":"numerale per '2' (forma sassone cause troviamo la t invece della z tedesca del '2')",
            "sunufatarungo":"hapax composta da sunu (figlio) e fatar (figlio) + suffisso patronimico - ung nelle forme del germanico (utilizzato per rendere figlio di)",
            "iro":"genitivo del pronome di 3 persona plurale (di loro)",
            "saro":"accusativo plurale (armature)",
            "rihtun":"3 persona plurale del preterito di rikten, verbo debole di 1 classe",
            "garutun":"garem, verbo debole di 1 classe",
            "se":"pronome 3 persona plurale maschile 'essi'",
            "iro":"genitivo del pronome di 3 persona plurale (di loro)",
            "gūdthamun":"composto gudth (battaglia) e ham (veste) corazze, 'camicia da battaglia, forma sassone (ū aveva dopo una nasale che cade per la spirante e provoca allungamento)",
            "gurtun":"3 persona plurale del preterito di gurten, verbo debole di 1 classe",
            "sih":"riflessivo",
            "iro":"genitivo del pronome di 3 persona plurale (di loro)",
            "suert":"forma aat di 'spada', col passaggio della d in t",
            "ana":"",
            "helidos":"termine sassone da helid, utilizzato come variante di ‘uomini’",
            "ubar":"sopra",
            "ringa":"anelli (metonimia per la cotta di maglia)",
            "do":"'allora', in ags. 'tha'",
            "sie":"pronome personale plurale maschile 'essi'",
            "to":"'verso'",
            "dero":"dimostrativo/articolo",
            "hiltu":"dativo singolare, sostantivo femminile, che significa 'battaglia'",
            "ritun":"3 persona plurale del preterito di ritan, verbo forte di 1 classe",
            "Hiltibrant":"Hildebrando",
            "gimahalta":"3 persona singolare del preterito di gimahalen, verbo debole di 1 classe",
            "Heribrantes":"Heribrando, genitivo",
            "sunu":"nominativo, figlio",
            "her":"dativo di 3 persona singolare maschile, forma ags a causa della h",
            "uuas":"3 persona singolare del preterito di wesan, verbo forte di 5 classe (wesan - was - warum), poi passaggio da s a r per rotacismo",
            "heroro":"nominativo maschile del comparativo",
            "man":"uomo",
            "ferahes":"'della vita', genitivo -es",
            "frotoro":"comparativo per 'più esperto'",
            "her":"egli",
            "fragen":"verbo debole di 3 classe",
            "gistuont":"3 persona singolare del preterito di gistantan (in ags standan), verbo forte di 6 classe (gistantan - stunt - stuontum - stantan)",
            "gistontun":"3 persona plurale (per il bisogno) di gistantan, verbo forte di 6 classe",
            "fohem":"dativo per 'con poche'",
            "uuortum":"parole",
            "wer":"pronome interrogativo per 'chi'",
            "sin":"possessivo 'suo'",
            "fater":"padre",
            "wari":"sempre da wesan, verbo forte di 5 classe, ma qui è un ottativo",
            "fireo":"genitivo 'degli uomini'",
            "in":"fra",
            "folche":"popolo",
            "eddo":"oppure",
            "welihhes":"genitivo interrogativo welih 'di quale'",
            "cnuosles":"stirpe",
            "du":"tu",
            "sis":"presente ottativo di sin, verbo atematico",
            "Ibu":"se",
            "du":"tu",
            "mi":"dativo del pronome di prima persona 'ih' 'a me'",
            "enan":"accusativo del numerale 'en', 'l'una' (forma sassone, in aat abbiamo elin)",
            "sages":"2 persona singolare del presente ottativo di sajen, verbo debole di 3 classe",
            "ik":"nominativo del pronome personale di prima persona “io” (antico sassone, nel caso di aat. sarebbe stato “ih”, non ha mutazione consonantica)",
            "mi":"dativo del pronome di prima persona 'ih' 'a me'",
            "de":"articolo 'le'",
            "odre":"'altre', forma ags, forma aat 'unter', presenta la caduta nasale con allungamento (come termini ingevoni) ma presenta le II MUT alla d (termine aat)",
            "uuet":"1 persona indicativo di witan, verbo preterito presente, in aat la forma era wissan, (forma sassone)",
            "chind":"figlio, forma aat",
            "in":"'nel'",
            "chunincriche":"dativo, chuni (re) + riche (regno)",
            "chud":"'nota'",
            "ist":"3 persona singolare indicativo del verbo essere",
            "mir":"dativo singolare",
            "al":"tutta",
            "irmindeot":"irmin (immenso) + deot (popolo)",
            "Hadubrant":"Adubrando",
            "gimahalta":"3 persona singolare del preterito di gimahalen, verbo debole di 1 classe",
            "Hiltibrantes":"Hildebrando",
            "sunu":"figlio",
            "Dat":"accusativo dell'articolo dimostrativo con funzione pronominale, non ha subito la II MUT (t)",
            "sagetun":"3 persona plurale presente indicativo di sagen, verbo debole di 3 classe, forma aat",
            "mi":"a me",
            "usere":"aggettivo possessivo di prima persona plurale, in aat doveva essere 'unsere'",
            "liuti":"nominativo plurale, forma aat perché presenta la II MUT (t)",
            "alte":"aggettivo forte da alt",
            "anti":"congiunzione 'and'",
            "frote":"aggettivo per sagge",
            "dea":"nominativo riferito alle genti (le quali)",
            "erhina":"avverbio, in ags si trova anche er",
            "warun":"preterito plurale di wesan, verbo forte di 5 classe",
            "dat":"congiunzione che",
            "Hiltibrant":"Hildebrando",
            "hætti":"hattan, verbo forte di 7 classe, forma sassone (in aat sarebbe heissan)",
            "min":"mio",
            "fater":"",
            "ih":"forma aat (prima era ik, forma sassone)",
            "heittu":"hattan, verbo forte di 7 classe, forma sassone (in aat sarebbe heissan)",
            "Hadubrant":"Adubrando",
            "Forn":"avverbio 'un tempo'",
            "her":"pronome di terza persona",
            "ostar":"avverbio per 'verso oriente'",
            "giweit":"3 persona singolare del preterito di witan del verbo forte di 1 classe, forma sassone, in aat sarebbe stata wissan",
            "floh":"preterito di fliohan, verbo forte di 2 classe (fliohan - flo - fluhun - flohan) ",
            "her":"pronome 3 persona singolare",
            "Otachres":"genitivo 'di Odoacre",
            "nid":"all'odio",
            "hina":"via",
            "miti":"preposizione con",
            "Theotrihhe":"Teodorico",
            "enti":"congiunzione aat ('and' con la II MUT)",
            "sinero":"aggetivo possessivo 'dei suoi'",
            "degano":"genitivo plurale di degan (seguace), forma aat per il passaggio del th in d",
            "filu":"aggettivo indeclinabile che regge il genitivo, forma anglosassone per 'molti'",
            "Her":"egli",
            "furlaet":"forma sassone, verbo forte di 7 classe, in aat è lezzan, liaz, liazzum, lazzan",
            "in":"in",
            "lante":"patria",
            "luttila":"il piccolo (little), forma sassone, in aat luzil",
            "sitten":"forma sassone, in aat sizzen",
            "prut":"della sposa",
            "in":"in",
            "bure":"casa",
            "barn":"il figlio",
            "unwahsan":"prefisso privativo, variazione di luttila e arbeo laosa",
            "arbeo":"genitivo plurale di eredità",
            "laosa":"privo",
            "her":"lui",
            "raet":"preterito singolare di ritan, verbo forte di 1 classe (ritan - reit - ritun - ritan)",
            "ostar":"avverbio per 'verso oriente'",
            "hina":"avverbio per 'via'",
            "Des":"di quello",
            "sid":"congiunzione per 'da quando'",
            "Detrihhe":"dativo singolare per 'a Teodorico'",
            "darba":"il bisogno/la mancanza (plurale tradotto a singolare)",
            "gistuontun":"3 persona plurale (per il bisogno) di gistantan, verbo forte di 6 classe",
            "fateres":"padre",
            "mines":"genitivo maschile, possessivo singolare maschile",
            "dat":"congiunzione",
            "uuas":"preterito del verbo wesan",
            "so":"avverbio per 'così'",
            "friuntlaos":"hapax formato da friunt (amici) e laos (privo)",
            "man":"uomo",
            "her":"egli",
            "was":"preterito verbo essere",
            "Otachre":"dativo singolare per 'con Odoacre'",
            "ummet":"avverbio per 'oltremodo'",
            "tirri":"forma sassone, in aat zirri, hapax per 'adirato'",
            "degano":"genitiov plurale, forma aat, in basso tedesco è 'thegan'",
            "dechisto":"superlativo per 'il più caro'",
            "miti":"per",
            "Deitrichhe":"Teodorico",
            "her":"egli",
            "was":"preterito verbo essere",
            "eo":"sempre",
            "folches":"genitivo per 'della schiera'",
            "at":"preposizione",
            "ente":"capo",
            "imo":"dativo per 'a lui'",
            "was":"preterito verbo essere",
            "eo":"sempre",
            "fehta":"in ags feoht, 'la battaglia'",
            "ti":"forma basso tedesca, in aat zi, avverbio per 'tocco' ",
            "leop":"caro",
            "chud":"aggettivo forte con funzione predicativa (era noto), forma aat hunt (caduta della nasale)",
            "was":"preterito verbo essere",
            "her":"egli",
            "chonnem":"prodi",
            "mannum":"uomini",
            "mi":"non",
            "waniu":"preterito di wannen,verbo debole di 1 classe",
            "ih":"io",
            "iu":"sempre",
            "lib":"vita",
            "habbe":"presente singolare ottativo del verbo habben, verbo debole di 3 classe",
            "Wettu":"'chiamare a testimone', 1 persona singolare di weizen, verbo debole",
            "irmingot":"'il grande Dio'",
            "quad":"3 persona preterito singolare di quedan, verbo forte di 5 classe (quedan - quad - quatum - quetan, alternanza grammaticale)",
            "Hiltibrant":"Hildebrando",
            "obana":"avverbio per 'su'",
            "ab":"preposizione per 'dal'",
            "hevane":"cielo",
            "dat":"che",
            "du":"tu",
            "neo":"avverbio per 'mai'",
            "dana":"avverbio per 'allora'",
            "halt":"avverbio per 'più'",
            "mit":"preposizione 'con'",
            "sus":"avverbio 'così'",
            "sippan":"parente",
            "man":"uomo",
            "dinc":"accusativo per 'contesa'",
            "ni":"avverbio per 'mai'",
            "gileitos":"preterito di gilenten, verbo debole di 1 classe",
            "Want":"3 persona del preterito singolare di wintan, verbo forte di 3 classe (wintan - want - wuntun - giwuntan)",
            "her":"egli",
            "do":"avverbio per 'allora'",
            "ar":"preposizione",
            "arme":"braccio",
            "wuntane":"participio preterito con funzione di aggettivo (verbo wintan), attorcigliate",
            "bauga":"accusativo plurale per 'bracciale/armille'",
            "cheisuringu":"composto",
            "gitan":"participio preterito di tuon, verbo atematico",
            "so":"congiunzione per 'siccome'",
            "imo":"dativo per 'a lui'",
            "se":"quelli",
            "der":"preposizione",
            "chuning":"Re",
            "gap":"preterito singolare di geban, verbo forte di 5 classe (geban - gab - gabun - geban)",
            "Huneo":"degli Unni",
            "truhtin":"il signore",
            "Dat":"ciò",
            "ih":"io",
            "dir":"dativo 'per te'",
            "it":"esso, forma sassone, forma aat iz",
            "nu":"avverbio per 'adesso'",
            "bi":"preposizione per 'come'",
            "huldi":"amicizia",
            "gibu":"1 persona singolare presente indicativo di geban, verbo forte di 5 classe",
            "Hadubrant":"Adubrando",
            "gimalta":"3 persona singolare del preterito di gimahalen, verbo debole di 1 classe",
            "Hiltibrantes":"Hildebrando",
            "sunu":"figlio",
            "Mit":"preposizione per 'con'",
            "geru":"lancia",
            "scal":"verbo preterito presente sculan",
            "man":"uomo",
            "geba":"accusativo singolare",
            "infahan":"verbo forte di 7 classe",
            "ort":"punta, nominativo",
            "widar":"preposizione per 'contro'",
            "orte":"punta, dativo cause of la preposizione",
            "du":"tu",
            "bist":"radice della coniugazione del verbo essere",
            "dir":"dativo 'per te'",
            "alter":"vecchio",
            "Hun":"Unno",
            "ummet":"avverbio per 'oltremodo'",
            "spaher":"scaltro",
            "spenis":"2 persona singolare dell'indicativo di spanan, verbo forte di 3 classe (spanan - spuon - suonum - gispanan)",
            "mih":"a me",
            "mit":"preposizione per 'con'",
            "dinem":"tue",
            "wortun":"parole",
            "wili":"da wellen, verbo anomalo",
            "mih":"me",
            "dinu":"aggettivo possessivo (strumentale in questo caso)",
            "speru":"lancia",
            "werpan":"forma basso tedesca, verbo forte di 3 classe (werpan - warp - wurpun - wurpan)",
            "Pist":"II MUT, to be, passaggio della b in p ",
            "also":"avverbio per 'così'",
            "gialtet":"participio preterito usato come aggettivo, verbo debole di 3 classe",
            "man":"uomo",
            "so":"così",
            "du":"tu",
            "ewin":"aggettivo eterno",
            "inwit":"accusativo singolare per inganno",
            "fortos":"2 persona singolare del preterito di foren, verbo debole",
            "Dat":"accusativo singolare del dimostrativo, usato anche come articolo (forma sassone per la d col taglio e la t)",
            "sagetun":"3 persona plurale presente indicativo di sagen, verbo debole di 3 classe, forma aat",
            "mi":"dativo del pronome di prima persona (a me)",
            "seolidante":"aggettivo composto seo (mare) e participio presente del verbo lidan (verbo forte di 1 classe)",
            "westar":"da ovest o verso ovest",
            "ubar":"preposizione sopra",
            "wentilseo":"accusativo formato da wenti (vandali) e seo (mare)",
            "dat":"congiunzione 'che'",
            "inan":"accusativo per pronome di 3 persona singolare (lui), la guerra lo prese, prese lui",
            "wic":"la guerra",
            "furnam":"3 persona singolare del preterito furneman, verbo forte di 4 classe (furneman - nam - namun - ginoman)",
            "tot":"morto",
            "ist":"3 persona singolare indicativo del verbo essere",
            "Hiltibrant":"Hildebrando",
            "Heribrantes":"Heribrando",
            "suno":"figlio",
            "Hiltibrant":"Hildebrante",
            "gimahalta":"3 persona singolare del preterito di gimahalen, verbo debole di 1 classe",
            "Heribrantes":"Heribando",
            "suno":"figlio",
            "Wela":"avverbio per 'bene'",
            "gisihu":"forma aat, in sassone è seon (allungamento di compenso), (gisehan - sah - satun - gisehan)",
            "ih":"io",
            "in":"preposizione 'dalle'",
            "dinem":"aggettivo possessivo di din tue", 
            "hrustim":"armi",
            "dat":"congiunzione 'che'",
            "du":"tu",
            "habes":"indicativo di haben, verbo debole di 3 classe",
            "heme":"patria (home)",
            "herron":"originariamente herrero, comparativo di herror che in aat è 'anziano, saggio', calco strutturale costruito sul modello di 'senior - senex + comparativo', sostituirà 'druht'", 
            "goten":"aggettivo per 'buono', forma aat",
            "dat":"congiunzione 'che'",
            "du":"tu",
            "noh":"avverbio per 'ancora'",
            "bi":"preposizione per 'in'",
            "desemo":"dativo di 'questo'",
            "riche":"regno", 
            "reccheo":"esule", 
            "ni":"avverbio 'non'",
            "wurti":"preterito indicativo di werdan verbo forte di 3 classe (werdan - ward - wurdon - giwortan, alternanza grammaticale)",
            "Welaga":"interiezione 'ahimè'", 
            "nu":"avverbio 'adesso'",
            "waltant":"possente",
            "got":"Dio",
            "quad":"3 persona preterito singolare di quedan, verbo forte di 5 classe (quedan - quad - quatum - quetan, alternanza grammaticale)",
            "Hiltibrant":"Hildebrando",
            "wewurt":"hapax, composto da dolore + wurt (fato pagano)",
            "skihit":"presente di skehan, verbo forte di 5 classe",
            "Ih":"io",
            "wallota":"waldon, verbo debole di 2 classe",
            "sumaro":"genitivo", 
            "enti":"congiunzione aat ('and' con la II MUT)",
            "wintro":"genitivo",
            "sehstic":"numerale per 60, in germanico reggono sempre il genitivo ('60 di estati e di inverni')",
            "ur":"preposizione 'dalla'",
            "lante":"patria, forma aat",
            "dar":"lì",
            "man":"uomo, qua inteso come capo (Teodorico)",
            "mih":"a me",
            "eo":"sempre",
            "scerita":"3 persona singolare di skerian, verbo debole", 
            "in":"preposizione 'nella'",
            "folc":"schiera",
            "sceotantero":"participio preterito sostantivato di skeotan, verbo forte di 2 classe (modo per dire 'arcieri')",
            "so":"eppure",
            "man":"uomo",
            "mir":"dativo singolare 'a me'",
            "at":"presso",
            "burc":"la cittadella",
            "enigeru":"aggettivo indefinito",
            "banun":"morte",
            "ni":"avverbio 'mai'",
            "gifasta":"3 persona singolare del preterito di un verbo debole di 3 classe",
            "Nu":"avverbio per 'adesso'",
            "scal":"verbo preterito presente (shall)", 
            "mih":"a me", 
            "suasat":"il proprio", 
            "chind":"figlio, forma aat", 
            "suertu":"strumentale, 'con la spada'", 
            "hauwan":"verbo forte di 7 classe",
            "breton":"infinito di un verbo debole di 2 classe, hapax, poggia su scal", 
            "mit":"preposizione per 'con'", 
            "sinu":"la sua", 
            "billiu":"brando, spada",
            "eddo":"oppure",
            "ih":"io",
            "imo":"dativo per 'a lui'",
            "ti":"preposizione per 'come'",
            "banin":"sostantivo maschile di uccisore",
            "werdan":"infinito dl verbo forte di 3 classe (werdan - ward - wurdon - giwortan, alternanza grammaticale)",
            "Doh" :"però",
            "maht":"poi, da maran, verbo preterito presente",
            "du":"tu",
            "nu":"avverbio per 'adesso'",
            "aodlihho":"avverbio per 'facilmente', audi + lih",
            "ibu":"congiunzione 'se'",
            "dir":"dativo 'per te'",
            "din":"il tuo",
            "ellen":"coraggio",
            "taoc":"verbo preterito presente tudan",
            "in":"preposizione (ma 'contro' in this case) ",
            "sus":"avverbio 'così'",
            "heremo":"vecchio",
            "man":"uomo",
            "hrusti":"armatura",
            "giwinnan":"verbo forte di 3 classe",
            "rauba":"spoglie di guerra",
            "birahanen":"verbo debole di 1 classe",
            "ibu":"congiunzione 'se'",
            "du":"tu",
            "dar":"là",
            "enic":"indefinito 'qualche'",
            "reht":"diritto",
            "habes":"indicativo di haben, verbo debole di 3 classe",
            "Der":"quello, funzione pronominale 'colui che'",
            "si":"3 ppersona singolare dell'ottativo del verbo essere",
            "doh":"congiunzione 'comunque'",
            "nu":"avverbio per 'adesso'",
            "argosto":"superlativo 'il più vile'",
            "quad":"3 persona preterito singolare di quedan, verbo forte di 5 classe (quedan - quad - quatum - quetan, alternanza grammaticale)",
            "Hiltibrant":"Hildebrando",
            "ostarliuto":"dei popoli d’oriente, genitivo plurale, ostar (dell’est) + liuto (popolo)",
            "der":"congiunzione 'che'",
            "dir":"dativo 'a te'",
            "nu":"avverbio 'adesso'",
            "wiges":"guerra",
            "warne":"ottativo presente di warnon, verbo debole 2 classe",
            "nu":"avverbio per 'adesso' (che)",
            "dih":"a te",
            "es":"ciò", 
            "so":"così",
            "wel":"bene", 
            "lustit":"lustan, verbo debole di 1 classe",
            "gudea":"il combattimento (elementi sassoni, in aat gunth)",
            "gimeinun":"reciproco",
            "niuse":"ottativo presente di niusen, verbo debole di 1 classe",
            "de":"colui che",
            "motti":"ottativo di muotan, forma sassone (in aat sarebbe muozzi)",
            "werdar":"chi dei 2",
            "sih":"accusativo, pronome riflessivo",
            "hiutu":"avverbio 'oggi'", 
            "dero":"genitivo 'delle'",
            "hregilo":"spoglie", 
            "rumen":"verbo debole di 1 classe", 
            "muotti":"ottativo di muotan, forma sassone (in aat sarebbe muozzi)",
            "erdo":"oppure", 
            "desero":"di queste",
            "brunnono":"corazze",
            "bedero":"ambedue",
            "uualtan":"verbo forte di 7 classe ",
            "Do":"allora",
            "lettun":"verbo forte di 7 classe, forma sassone, in aat lazzan", 
            "se":"essi",
            "ærist":"avverbio 'dapprima'",
            "asckim":"kenning per 'scudi' (frassini)",
            "scritan":"infinito verbo forte di 1 classe",
            "scarpen":"taglienti (sharp)",
            "scurim":"scariche",
            "dat":"ciò, riferito alla scarica",
            "in":"nei",
            "dem":"loro",
            "sciltim":"scudi", 
            "stont":"stantan, in ags standan, verbo forte di 6 classe",
            "Do":"allora",
            "stoptun":"stopjan, verbo debole di 1 classe",
            "to":"avverbio 'insieme'",
            "samane":"avverbio 'insieme'",
            "staimbort":"kenning di 'scudi'",
            "chlubun":"chliodan, verbo forte di 2 classe",
            "heuwun":"hawan, verbo forte di 7 classe",
            "harmlicco":"avverbio 'violentemente'",
            "huitte":"gli scintillanti, forma basso tedesca, in aat huizz",
            "scilti":"scudi",
            "unti":"congiunzione e",
            "im":"a loro",
            "iro":"di essi (possessivo in questo caso, i loro)",
            "lintun":"tigli, sempre riferendosi agli scudi",
            "luttilo":"piccoli",
            "wurtun":"preterito indicativo di werdan verbo forte di 3 classe (werdan - ward - wurdon - giwortan, alternanza grammaticale)",
            "giwigan":"participio preterito di wigan, verbo forte di 1 classe (witan - weih - witum - giwitan)",
            "miti":"con",
            "wabnum":"armi",
            // Aggiungi altre parole e le loro informazioni qui
        };
        return info[word] || "No information available for this word.";
    }

    // Aggiungere evento click ad ogni parola
    textElement.innerHTML = textElement.innerHTML.split(' ').map(word => `<span class="clickable">${word}</span>`).join(' ');
    const words = document.querySelectorAll(".clickable");

    words.forEach(wordElement => {
        wordElement.addEventListener("click", function(event) {
            const word = event.target.textContent;
            showInfoBox(word);
            event.stopPropagation(); // Previene la propagazione dell'evento di click
        });
    });

    // Nascondere la finestra informativa quando si clicca altrove
    document.addEventListener("click", function(event) {
        if (!event.target.classList.contains("clickable")) {
            infoBox.classList.add('hidden');
        }
    });
});